spring:
  application:
    name: kinero

  datasource:
    url: jdbc:postgresql://localhost:5432/kinero_db
    username: kinero_user
    password: kinero_password

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
